name: Compression Benchmark

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest  # Use Linux runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git cmake tar gzip zstd lz4
          which gzip || echo "Gzip not found!"

      - name: Clone and Build lzbench
        run: |
          git clone https://github.com/inikep/lzbench.git
          cd lzbench
          make -j$(nproc)

      - name: Run Benchmarks
        run: |
          mkdir -p results
          cd lzbench
          
          # Create a test file (100MB of random data)
          dd if=/dev/urandom of=../testfile bs=1M count=100

          echo "Running benchmarks on compression tools..."

          # Run lz4
          ./lzbench -ezstd_fast,1,st -ezstd_fast,1,mt \
                    -ezstd_fast,5 -ezstd_fast,5,mt \
                    -ezstd_fast,19,st -ezstd_fast,19,mt \
                    -elz4fast,1,st -elz4fast,1,mt \
                    -elz4fast,9,st -elz4fast,9,mt \
                    -elz4fast,17,st -elz4fast,17,mt \
                    -i10,20 ../testfile | tee ../results/lzbench_results.txt

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: lzbench-results
          path: results/lzbench_results.txt